apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-kv
spec:
  provider: azure
  secretObjects:
  - secretName: db-secret
    type: Opaque
    data:
    - objectName: db-password
      key: password
    - objectName: db-url
      key: database_url
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: "fc6ba135-edd1-4bc6-9f20-6a4a465a711e"
    keyvaultName: "my-hn-kv-19469"
    cloudName: ""
    objects: |
      array:
        - |
          objectName: db-password
          objectType: secret
        - |
          objectName: db-url
          objectType: secret
    tenantId: "d3c187bb-f433-492a-8866-6aca0c938873"
